language: rust
sudo: false

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --example test_authorization_header
  - cargo run --example test_get
  - cargo run --example test_post
