[package]

name = "oauth-client"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license-file="LICENSE"
readme = "README.md"
repository = "https://github.com/gifnksm/oauth-client-rs"
description = "OAuth client for Rust"

